# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /home/runner/workspace/certbot/config/archive/rpc.meechain.run.place
cert = /home/runner/workspace/certbot/config/live/rpc.meechain.run.place/cert.pem
privkey = /home/runner/workspace/certbot/config/live/rpc.meechain.run.place/privkey.pem
chain = /home/runner/workspace/certbot/config/live/rpc.meechain.run.place/chain.pem
fullchain = /home/runner/workspace/certbot/config/live/rpc.meechain.run.place/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 1008db9b04bd6b36dd4f310e18259956
pref_challs = dns-01,
config_dir = /home/runner/workspace/certbot/config
work_dir = /home/runner/workspace/certbot/work
logs_dir = /home/runner/workspace/certbot/logs
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
