events {}

http {
  server {
    listen 443 ssl;
    server_name rpc.meechain.run.place;

    ssl_certificate     /home/runner/workspace/certbot/config/live/rpc.meechain.run.place/fullchain.pem;
    ssl_certificate_key /home/runner/workspace/certbot/config/live/rpc.meechain.run.place/privkey.pem;

    access_log /home/runner/workspace/logs/access.log;
    error_log  /home/runner/workspace/logs/error.log;

    location / {
      proxy_pass http://localhost:8080;
    }
  }
}
